### PR TITLE
Remove drawer from android

### PR DESCRIPTION
**Pull request by chirag-singhal**
Solves #170 

## Changelog
 - Removes sidebar/drawer from android

**This needs to be merged only after #162 is done!!**

### CODE REVIEW

**Comment by stealthanthrax** [comment]
@chirag-singhal , why does this have the async storage code ? 😅

**Comment by chirag-singhal** [comment]
@stealthanthrax android drawer was used in bookmark screen as well. So i had to work on top of my branch.

**Comment by stealthanthrax** [comment]
@chirag-singhal , makes sense.

**Comment by anku255** [comment]
This PR is not needed now.

**Pull request closed without merging**
