### PR TITLE
Example page minor fixes and ignore warnings

### PR DESCRIPTION
**Pull request by chirag-singhal**
## Changelog

 * Font Size for description
 * Spacing between use cases
 * Disable warning messages

### CODE REVIEW

**Review by YashKumarVerma — COMMENTED** [review]
While testing, i can still see the log box being displayed with the AsyncStorage Message

WhatsApp Image 2020-08-20 at 1 21 02 AM

**Comment by chirag-singhal** [comment]
@YashKumarVerma Fixed!

**Review by anku255 — COMMENTED** [review]
@chirag-singhal  I can still see all these Errors. We have removed the community screens then where are these being used. If they are being used in any other example then probably add a comment for them too. 


Screenshot 2020-08-20 at 2 06 17 PM




Also, use the following syntax to be consistent in the file.

```js
const {LogBox} = require('react-native');
```

**Comment by chirag-singhal** [comment]
@anku255 Warnings is removed from the App and these will still be shown on terminal

**Comment by anku255** [comment]
@chirag-singhal Oh! that makes sense.

**Pull request merged**
