### PR TITLE
Merged Multilist in a single Flat List and updated FlatList Screens

### LINKED ISSUE #112: Implement new FlatList Screen
## UseCases
- [x] Horizontal Mode
- [x] Pull To Refresh
- [ ] Separator Support
    - Currently present but not optional in the demo
- [x] Multiple Column Support
   - ToDo
- [x] Header Support
    - Currently present but not optional in the demo
- [x] Footer Support
    - Currently present but not optional in the demo
- [x] ScrollToIndex Support
- [ ] Scroll Loading

## E2E Tests

- [ ] List should be scrollable and each item should be tappable
- [ ] Horizontal list should be scrollable and each item should be tappable

### PR DESCRIPTION
**Pull request by stealthanthrax**
## Summary
Fixes #112

Restyled flat lists and merged multi-column flat lists into a single component with simple flat list.
## Changelog

[General] [Changed] - Merged Multilist in a single Flat List and updated FlatList Screens

## Test Plan

Screenshot 2020-08-16 at 5 40 58 AM

### CODE REVIEW

**Comment by Xtremilicious** [comment]
@stealthanthrax shouldn't this PR be directed towards the `mlh-fellowship-migrated-ui-changes` branch?

**Comment by stealthanthrax** [comment]
@Xtremilicious , what is the difference between the two of them?

**Comment by Xtremilicious** [comment]
> @Xtremilicious , what is the difference between the two of them?

@stealthanthrax  From what I saw, the `mlh-fellowship-migrated-ui-changes` branch contains some commits from the upstream `master` as well as some extra commits by our team. The `mlh-fellowship-ui-changes` branch seems to be far behind in the commits from upstream `master`. 

Here's the full comparison: https://github.com/MLH-Fellowship/react-native/compare/mlh-fellowship-ui-changes...MLH-Fellowship:mlh-fellowship-migrated-ui-changes

**Comment by stealthanthrax** [comment]
Thanks @Xtremilicious 🖖  . Looks like I'll have to create a new PR.

**Comment by stealthanthrax** [comment]
Re-Opened here https://github.com/MLH-Fellowship/react-native/pull/216

**Pull request closed without merging**
